INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME)
VALUES ('Томас', 'Харрис');
INSERT INTO AUTHORS (FIRST_NAME, LAST_NAME)
VALUES ('Дарья', 'Донцова');

INSERT INTO BOOKS (TITLE, ISBN)
VALUES ('Молчание ягнят', '5-17-017776-3');
INSERT INTO BOOKS (TITLE, ISBN)
VALUES ('Жираф – гроза пингвинов', '978-5-04-113895-0');

INSERT INTO GENRES (NAME)
VALUES ('комедия');
INSERT INTO GENRES (NAME)
VALUES ('трагедия');
INSERT INTO GENRES (NAME)
VALUES ('драма');
INSERT INTO GENRES (NAME)
VALUES ('ужасы');
INSERT INTO GENRES (NAME)
VALUES ('рассказ');
INSERT INTO GENRES (NAME)
VALUES ('роман');
INSERT INTO GENRES (NAME)
VALUES ('повесть');
INSERT INTO GENRES (NAME)
VALUES ('пьеса');

INSERT INTO BOOK_AUTHORS (BOOK_ID, AUTHOR_ID)
VALUES (1, 1);
INSERT INTO BOOK_AUTHORS (BOOK_ID, AUTHOR_ID)
VALUES (2, 2);
INSERT INTO BOOK_GENRES (BOOK_ID, GENRE_ID)
VALUES (1, 3);
INSERT INTO BOOK_GENRES (BOOK_ID, GENRE_ID)
VALUES (1, 6);
INSERT INTO BOOK_GENRES (BOOK_ID, GENRE_ID)
VALUES (2, 4);

INSERT INTO COMMENTS (COMMENTED_BY, TEXT, BOOK_ID)
VALUES ('Генри Форд', 'Прочёл на одном дыхании!', 2);
INSERT INTO COMMENTS (COMMENTED_BY, TEXT, BOOK_ID)
VALUES ('Карл Маркс', 'Не впечатлило!', 1);