spring:
  batch:
    initializer:
      enabled: false
    job:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
    generate-ddl: false
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://127.0.0.1/test?createDatabaseIfNotExist=true&characterEncoding=utf8
    username: dev
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

job:
  reports:
    chunksize: 1000
    filter: ALL
    outputFileName: c:\\tmp\tickets_report.xlsx

logging:
  level:
    root: debug
