books-per-page-count: 10

server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:library
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: false

  endpoint:
    health:
      show-details: always
      enabled: true
    logfile:
      external-file: logs/app.log
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
    metrics:
      enabled: true

  health:
    defaults:
      enabled: true

logging:
  level:
    ROOT: DEBUG
  file:
    name: logs/app.log